environment:
  matrix:
  - julia_version: 1.1
  - julia_version: 1.2
  - julia_version: nightly
platform:
  - x86
  - x64
matrix:
  allow_failures:
  - julia_version: nightly
  - julia_version: 1.2
notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))
build_script:
  - C:\julia\bin\julia -e 'using Pkg; Pkg.Registry.add("General")'
  - C:\julia\bin\julia -e "using Pkg; Pkg.Registry.add(RegistrySpec(url = \"https://github.com/haberdashPI/LabRegistry.jl\"))"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"
test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
