language: julia
os:
  - linux
  - osx
julia:
  - 1.1
  - 1.2
  - nightly
script:
- julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url = "https://github.com/haberdashPI/LabRegistry.jl"))'
- julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
